_wandb:
    value:
        cli_version: 0.23.1
        e:
            xyzy52nnrd4mp3xqeqa1wkcdgj0gm50l:
                args:
                    - --checkpoint-dir
                    - out-posreg-6layer-until-mlp
                    - --experiment-name
                    - nope-6layer-until-first-mlp
                    - --n-samples
                    - "24"
                codePath: analysis_scripts/tsne_unique_vs_random.py
                codePathLocal: analysis_scripts/tsne_unique_vs_random.py
                cpu_count: 128
                cpu_count_logical: 128
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "3832434667520"
                        used: "405557104640"
                email: matan13av@gmail.com
                executable: /home/nlp/matan_avitan/.conda/envs/py312/bin/python
                git:
                    commit: 935ec8924524b5952a7c6e78ae80e026044f4d27
                    remote: git@github.com:MatanAvitan/nopos_locating_new.git
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-d76056a1-a64b-df4c-63e6-486693380c5d
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-f66b39ed-9965-9032-3d6e-36acec2f8a2b
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-130ea43a-d14d-ad32-a080-0d0603dfe760
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-16b54c80-6975-58e2-ca10-84b260b12a69
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-92573f03-7d19-3859-aa51-47d17c902e78
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-9d4e5ced-a020-7d98-1a80-b4e3366b797e
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-eaf71afd-8768-c554-ba8b-91c30295b7b3
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-76b83a0e-d509-563d-d6eb-39a8ce79c95b
                host: dsinlp01
                memory:
                    total: "1081493651456"
                os: Linux-5.14.0-570.52.1.el9_6.x86_64-x86_64-with-glibc2.34
                program: /home/nlp/matan_avitan/git/nopos_locating_new/analysis_scripts/tsne_unique_vs_random.py
                python: CPython 3.12.8
                root: /home/nlp/matan_avitan/git/nopos_locating_new
                startedAt: "2026-01-18T14:38:00.242988Z"
                writerId: xyzy52nnrd4mp3xqeqa1wkcdgj0gm50l
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 53
                - 105
            "2":
                - 1
                - 5
                - 53
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.8
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
checkpoint_steps:
    value:
        - 500
        - 2000
        - 5000
        - 10000
        - 15000
        - 20000
comparison:
    value: unique_vs_random
experiment:
    value: nope-6layer-until-first-mlp
layers:
    value:
        - post_ln2
        - mlp_hidden
        - post_mlp
n_samples:
    value: 24
note:
    value: Each sample i has i unique prefix tokens
