_wandb:
    value:
        cli_version: 0.23.1
        e:
            ory1r17q6tkk1p3puk86a4ucbh2z546f:
                args:
                    - --checkpoint-dir
                    - out-posreg-6layer-until-mlp
                    - --experiment-name
                    - causal-intervention-v3-fixed
                codePath: analysis_scripts/causal_intervention_v3.py
                codePathLocal: analysis_scripts/causal_intervention_v3.py
                cpu_count: 128
                cpu_count_logical: 128
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "3832434667520"
                        used: "405674184704"
                email: matan13av@gmail.com
                executable: /home/nlp/matan_avitan/.conda/envs/py312/bin/python
                git:
                    commit: 05ee8102da8f342ddc7174cf699be666761b2410
                    remote: git@github.com:MatanAvitan/nopos_locating_new.git
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-d76056a1-a64b-df4c-63e6-486693380c5d
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-f66b39ed-9965-9032-3d6e-36acec2f8a2b
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-130ea43a-d14d-ad32-a080-0d0603dfe760
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-16b54c80-6975-58e2-ca10-84b260b12a69
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-92573f03-7d19-3859-aa51-47d17c902e78
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-9d4e5ced-a020-7d98-1a80-b4e3366b797e
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-eaf71afd-8768-c554-ba8b-91c30295b7b3
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-76b83a0e-d509-563d-d6eb-39a8ce79c95b
                host: dsinlp01
                memory:
                    total: "1081493651456"
                os: Linux-5.14.0-570.52.1.el9_6.x86_64-x86_64-with-glibc2.34
                program: /home/nlp/matan_avitan/git/nopos_locating_new/analysis_scripts/causal_intervention_v3.py
                python: CPython 3.12.8
                root: /home/nlp/matan_avitan/git/nopos_locating_new
                startedAt: "2026-01-18T22:53:59.164856Z"
                writerId: ory1r17q6tkk1p3puk86a4ucbh2z546f
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.8
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
checkpoint_steps:
    value:
        - 500
        - 1000
        - 1500
        - 2000
        - 2500
        - 3000
        - 3500
        - 4000
        - 4500
        - 5000
        - 5500
        - 6000
        - 6500
        - 7000
        - 7500
        - 8000
        - 8500
        - 9000
        - 9500
        - 10000
        - 10500
        - 11000
        - 11500
        - 12000
        - 12500
        - 13000
        - 13500
        - 14000
        - 14500
        - 15000
        - 15500
        - 16000
        - 16500
        - 17000
        - 17500
        - 18000
        - 18500
        - 19000
        - 19500
        - 20000
intervention_token:
    value: 2000
n_samples:
    value: 24
