_wandb:
    value:
        cli_version: 0.23.1
        e:
            zofbd304ns2hz1wao3ccwav4rnj2w4fz:
                args:
                    - --checkpoint-dir
                    - out-posreg-6layer-until-mlp
                    - --experiment-name
                    - causal-intervention-k
                    - --max-k
                    - "24"
                    - --n-copies
                    - "10"
                codePath: analysis_scripts/causal_intervention_k.py
                codePathLocal: analysis_scripts/causal_intervention_k.py
                cpu_count: 128
                cpu_count_logical: 128
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "3832434667520"
                        used: "405670125568"
                email: matan13av@gmail.com
                executable: /home/nlp/matan_avitan/.conda/envs/py312/bin/python3
                git:
                    commit: 05ee8102da8f342ddc7174cf699be666761b2410
                    remote: git@github.com:MatanAvitan/nopos_locating_new.git
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-d76056a1-a64b-df4c-63e6-486693380c5d
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-f66b39ed-9965-9032-3d6e-36acec2f8a2b
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-130ea43a-d14d-ad32-a080-0d0603dfe760
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-16b54c80-6975-58e2-ca10-84b260b12a69
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-92573f03-7d19-3859-aa51-47d17c902e78
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-9d4e5ced-a020-7d98-1a80-b4e3366b797e
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-eaf71afd-8768-c554-ba8b-91c30295b7b3
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-76b83a0e-d509-563d-d6eb-39a8ce79c95b
                host: dsinlp01
                memory:
                    total: "1081493651456"
                os: Linux-5.14.0-570.52.1.el9_6.x86_64-x86_64-with-glibc2.34
                program: /home/nlp/matan_avitan/git/nopos_locating_new/analysis_scripts/causal_intervention_k.py
                python: CPython 3.12.8
                root: /home/nlp/matan_avitan/git/nopos_locating_new
                startedAt: "2026-01-18T20:14:34.394509Z"
                writerId: zofbd304ns2hz1wao3ccwav4rnj2w4fz
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 13
                - 16
            "4": 3.12.8
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
checkpoint_steps:
    value:
        - 1000
        - 2000
        - 3000
        - 4000
        - 5000
        - 6000
        - 7000
        - 8000
        - 9000
        - 10000
        - 11000
        - 12000
        - 13000
        - 14000
        - 15000
        - 16000
        - 17000
        - 18000
        - 19000
        - 20000
max_k:
    value: 24
n_copies:
    value: 10
